import { _mock } from './_mock';
import { _tags } from './assets';

// ----------------------------------------------------------------------

const GB = 1000000000 * 24;

const FOLDERS = ['Docs', 'Projects', 'Work', 'Training', 'Sport', 'Foods'];
const CLINIC_CORP = ['Altima_Barrie-Gozer_16001', 'Altima_Barrie-Gozer_16001', 'Altima_Barrie-Gozer_16001', 'Altima_Barrie-Gozer_16001', 'Altima_Barrie-Gozer_16001', 'Altima_Barrie-Gozer_16001'];
const CLINIC =  [
  {
    id: 1,
    office_number: "",
    data_Path: "camgara_dental",
    clinic_code: "",
    corp_id: "123dental"+"_"+"BC-010 Camgara",
    clinic_name: "BC-010 Camgara",
    clinic_address: "",
    clinic_address1: "",
    clinic_postal: "",
    clinic_city: "",
    clinic_province: "",
    country: "CA",
   clinic_phone: "",
    clinic_fax: "",
   clinic_email: "",
    clinic_appointmentunit: 10,
    current_app: "Tracker",
    runLedgerBalance: false,
    idclinics: 25,
    dest_db: "camgaratracker",
    cutoff_date: "2012-08-25T00:00:00",
    acquistionDate: "2017-08-25T00:00:00",
      firstTransId: "0",
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "dmy",
    stage: "5-Moved to Production",
    todo: "none",
    actioBy: "None <>",
    asana_url: "",
    multiClinicJail: false,
    jailDataDir: "",
    locationId: "",
    comments: "",
    separateMultiClinicJail: false,
    swellcx_locId: "0",
    swellcx_teamId: "0",
    swellcx_campaign: "0",
    timezone: "+00:00",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status:"active",
    staff: null,
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "123Dentist-12001",
    corp: null,
    pmsName: "Tracker",
    pms: null,
    payMethodData: null
  },
  {
    id: 2,
    office_number: "",
    data_Path: "barrie",
    clinic_code: "1138",
    corp_id: "altima"+ "_" + "Altima Barrie",
    clinic_name: "Altima Barrie",
    clinic_address: "75 Collier Street",
    clinic_address1: "",
    clinic_postal: "L4M1G7",
    clinic_city: "Barrie",
    clinic_province: "ON",
    country: "CA",
   clinic_phone: "",
    clinic_fax: "",
   clinic_email: "",
    clinic_appointmentunit: 10,
    current_app: "Dentrix G6",
    runLedgerBalance: false,
    idclinics: 30,
    dest_db: "barrie",
    cutoff_date: "2014-01-01T00:00:00",
    acquistionDate: "2013-05-28T00:00:00",
      firstTransId: "0",
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "ymd",
    stage: "5-Moved to Production",
    todo: "None",
    actioBy: "None",
    asana_url: "",
    multiClinicJail: false,
    jailDataDir: null,
    locationId: null,
    comments: null,
    separateMultiClinicJail: false,
    swellcx_locId: null,
    swellcx_teamId: null,
    swellcx_campaign: null,
    timezone: "+00:00",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status: "active",
    staff: null,
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "ALTIMA-1015",
    corp: null,
    pmsName: "Dentrix G6",
    pms: null,
    payMethodData: null
  },
  {
    id: 3,
    office_number: "",
    data_Path: "bayview",
    clinic_code: "1114",
    corp_id: "altima" + "_" + "Altima Bayview",
    clinic_name: "Altima Bayview Village Dental Centre",
    clinic_address: "2885 Bayview Avenue",
    clinic_address1: "Unit #4",
    clinic_postal: "M2K0A3",
    clinic_city: "North York",
    clinic_province: "ON",
    country: "CA",
   clinic_phone: "",
    clinic_fax: "",
   clinic_email: "",
    clinic_appointmentunit: 10,
    current_app: "Dentrix G6",
    runLedgerBalance: true,
    idclinics: 4,
    dest_db: "bayview",
    cutoff_date: "2014-01-01T00:00:00",
    acquistionDate: "2013-06-10T00:00:00",
      firstTransId: "0",
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "dmy",
    stage: "5-Moved to Production",
    todo: "None",
    actioBy: "None",
    asana_url: "",
    multiClinicJail: false,
    jailDataDir: null,
    locationId: null,
    comments: null,
    separateMultiClinicJail: false,
    swellcx_locId: null,
    swellcx_teamId: null,
    swellcx_campaign: null,
    timezone: "+00:00",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status:"active",
    staff: null,
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "ALTIMA-1015",
    corp: null,
    pmsName: "Dentrix G6",
    pms: null,
    payMethodData: null
  },
  {
    id: 4,
    office_number: "",
    data_Path: "camgara_dental_data2",
    clinic_code: "",
    corp_id: "12002" + "_" + "Camgara Dental",
    clinic_name: "Camgara Randall Allen",
    clinic_address: "Camgara Dental Group, 7575 Cambie St.",
    clinic_address1: "",
    clinic_postal: "V6P 3H6",
    clinic_city: "Vancouver",
    clinic_province: "BC",
    country: "CA",
   clinic_phone: "(604) 325-8232",
    clinic_fax: "",
   clinic_email: "info@camgaradental.com",
    clinic_appointmentunit: 10,
    current_app: "Maxident",
    runLedgerBalance: false,
    idclinics: 14,
    dest_db: "camgara2",
    cutoff_date: "2012-08-25T00:00:00",
    acquistionDate: "2017-08-25T00:00:00",
      firstTransId: "0",
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "dmy",
    stage: "5-Moved to Production",
    todo: "none",
    actioBy: "",
    asana_url: "",
    multiClinicJail: false,
    jailDataDir: "",
    locationId: "",
    comments: "Camgara Dental Group\r\n7575 Cambie St\r\nVancouver, BC\r\nV6P 3H6\r\n\r\n(604) 325-8232",
    separateMultiClinicJail: false,
    swellcx_locId: "0",
    swellcx_teamId: "0",
    swellcx_campaign: "0",
    timezone: "+00:00",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status: "active",
    staff: null,
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "123Dental2 -12002",
    corp: null,
    pmsName: "Maxident",
    pms: null,
    payMethodData: null
  },
  {
    id: 5,
    office_number: "112",
    data_Path: "bible_hill",
    clinic_code: "1120",
    corp_id: "altima" +"_" + "Bible Hill",
    clinic_name: "Bible Hill",
    clinic_address: "336 Pictou Road",
    clinic_address1: "",
    clinic_postal: "B2N6H3",
    clinic_city: "Truro",
    clinic_province: "NS",
    country: "CA",
   clinic_phone: "",
    clinic_fax: "",
   clinic_email: "",
    clinic_appointmentunit: 10,
    current_app: "Abledent",
    runLedgerBalance: false,
    idclinics: 10,
    dest_db: "biblehill",
    cutoff_date: "2014-01-01T00:00:00",
    acquistionDate: "2013-04-12T00:00:00",
      firstTransId: "10537",
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "dmy",
    stage: "5-Moved to Production",
    todo: "None",
    actioBy: "None",
    asana_url: "",
    multiClinicJail: false,
    jailDataDir: null,
    locationId: null,
    comments: null,
    separateMultiClinicJail: false,
    swellcx_locId: null,
    swellcx_teamId: null,
    swellcx_campaign: null,
    timezone: "15",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status: "active",
    staff: null,
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "ALTIMA-1015",
    corp: null,
    pmsName: "Abledent",
    pms: null,
    payMethodData: null
  },
  {
    id: 6,
    office_number: "1144",
    data_Path: "strathroy",
    clinic_code: "1144",
    corp_id: "altima" + "_"+ "Brightview Dental",
    clinic_name: "Brightview Dental Strathroy",
    clinic_address: "11 Methcalfe St W #1",
    clinic_address1: "",
    clinic_postal: "N7G1M7",
    clinic_city: "Strathroy",
    clinic_province: "ON",
    country: "CA",
   clinic_phone: "5192452020",
    clinic_fax: "",
   clinic_email: "strathroy@brightviewdental.ca",
    clinic_appointmentunit: 10,
    current_app: "Tracker",
    runLedgerBalance: true,
    idclinics: 36,
    dest_db: "strathroy",
    cutoff_date: "2014-01-01T00:00:00",
    acquistionDate: null,
      firstTransId: null,
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "dmy",
    stage: "5-Moved to Production",
    todo: "None",
    actioBy: "None",
    asana_url: "",
    multiClinicJail: false,
    jailDataDir: null,
    locationId: null,
    comments: null,
    separateMultiClinicJail: false,
    swellcx_locId: null,
    swellcx_teamId: null,
    swellcx_campaign: null,
    timezone: "+00:00",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status: "active",
    staff: null,
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "ALTIMA-1015",
    corp: null,
    pmsName: "Tracker",
    pms: null,
    payMethodData: null
  },
  {
    id: 7,
    office_number: "",
    data_Path: "wheatland_dental",
    clinic_code: "",
    corp_id: "mazadreh" + "_" + "Wheatland Dental",
    clinic_name: "Wheatland Dental Centre",
    clinic_address: "520 Centre St.",
    clinic_address1: "",
    clinic_postal: "S0H 0B0",
    clinic_city: "Assiniboia",
    clinic_province: "Saskatchewan",
    country: "CA",
   clinic_phone: "(306) 642-4435",
    clinic_fax: "",
   clinic_email: "",
    clinic_appointmentunit: 15,
    current_app: "Power Practice",
    runLedgerBalance: false,
    idclinics: 3,
    dest_db: "wheatlanddental",
    cutoff_date: "1970-01-01T00:00:00",
    acquistionDate: "2012-05-04T00:00:00",
      firstTransId: "0",
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "dmy",
    stage: "5-Moved to Production",
    todo: "Move to Production Server",
    actioBy: "None <>",
    asana_url: "https://app.asana.com/0/278014366639733/1116672445912931/f",
    multiClinicJail: false,
    jailDataDir: "",
    locationId: "",
    comments: "",
    separateMultiClinicJail: false,
    swellcx_locId: "0",
    swellcx_teamId: "0",
    swellcx_campaign: "0",
    timezone: "15",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status:"active",
    staff: "default@edmsdental.com",
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "Mazadreh (Dental Look)-9001",
    corp: null,
    pmsName: "Power Practice",
    pms: null,
    payMethodData: null
  },
  {
    id: 8,
    office_number: "1015",
    data_Path: "college",
    clinic_code: "7002",
    corp_id: "altima" + "_" + "College Clinic",
    clinic_name: "College Clinic",
    clinic_address: "979 College Street",
    clinic_address1: "",
    clinic_postal: "M6H1A6",
    clinic_city: "Toronto",
    clinic_province: "ON",
    country: "CA",
   clinic_phone: "",
    clinic_fax: "",
   clinic_email: "",
    clinic_appointmentunit: 10,
    current_app: "Dentrix G6",
    runLedgerBalance: false,
    idclinics: 63,
    dest_db: "college",
    cutoff_date: "2014-01-01T00:00:00",
    acquistionDate: "2012-07-06T00:00:00",
      firstTransId: "0",
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "dmy",
    stage: "5-Moved to Production",
    todo: "None",
    actioBy: "None",
    asana_url: "",
    multiClinicJail: false,
    jailDataDir: null,
    locationId: null,
    comments: null,
    separateMultiClinicJail: false,
    swellcx_locId: null,
    swellcx_teamId: null,
    swellcx_campaign: null,
    timezone: "+00:00",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status: "active",
    staff: null,
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "ALTIMA-1015",
    corp: null,
    pmsName: "Dentrix G6",
    pms: null,
    payMethodData: null
  },
  {
    id: 9,
    office_number: "",
    data_Path: "coxwell",
    clinic_code: "2204",
    corp_id: "altima"+ "_" + "Coxwell",
    clinic_name: "Coxwell",
    clinic_address: "",
    clinic_address1: "",
    clinic_postal: "",
    clinic_city: "",
    clinic_province: "",
    country: "CA",
   clinic_phone: "",
    clinic_fax: "",
   clinic_email: "",
    clinic_appointmentunit: 10,
    current_app: "Dentrix G6",
    runLedgerBalance: false,
    idclinics: 46,
    dest_db: "coxwell",
    cutoff_date: "2014-01-01T00:00:00",
    acquistionDate: "2012-07-06T00:00:00",
      firstTransId: "0",
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "ymd",
    stage: "5-Moved to Production",
    todo: "None",
    actioBy: "None",
    asana_url: "",
    multiClinicJail: false,
    jailDataDir: null,
    locationId: null,
    comments: null,
    separateMultiClinicJail: false,
    swellcx_locId: null,
    swellcx_teamId: null,
    swellcx_campaign: null,
    timezone: "+00:00",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status:"active",
    staff: null,
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "ALTIMA-1015",
    corp: null,
    pmsName: "Dentrix G6",
    pms: null,
    payMethodData: null
  },
  {
    id: 10,
    office_number: "1504",
    data_Path: "grasslands",
    clinic_code: "1504",
    corp_id: "altima" + "_" + "RDG - Grasslands",
    clinic_name: "RDG - Grasslands",
    clinic_address: "4533 Gordon Road",
    clinic_address1: "",
    clinic_postal: "S4W3B7",
    clinic_city: "Regina",
    clinic_province: "SK",
    country: "CA",
   clinic_phone: "",
    clinic_fax: "",
   clinic_email: "",
    clinic_appointmentunit: 10,
    current_app: "Dentrix G4",
    runLedgerBalance: false,
    idclinics: 57,
    dest_db: "grasslands",
    cutoff_date: "2014-01-01T00:00:00",
    acquistionDate: null,
      firstTransId: null,
    prodDate: "EntryDate",
    colDate: "EntryDate",
    dateFormat: "ymd",
    stage: "5-Moved to Production",
    todo: "None",
    actioBy: "None",
    asana_url: "",
    multiClinicJail: false,
    jailDataDir: null,
    locationId: null,
    comments: null,
    separateMultiClinicJail: false,
    swellcx_locId: null,
    swellcx_teamId: null,
    swellcx_campaign: null,
    timezone: "+00:00",
    setup_Date: "2020-09-27T00:00:00",
    goLive_Date: null,
    active: true,
    status:"active",
    staff: null,
    data_path_source: null,
    chargeAdj: null,
    collectionAdj: null,
    corp_Name: "ALTIMA-1015",
    corp: null,
    pmsName: "Dentrix G4",
    pms: null,
    payMethodData: null
  }];
 

const FILES = [
  'cover-2.jpg',
  'design-suriname-2015.mp3',
  'expertise-2015-conakry-sao-tome-and-principe-gender.mp4',
  'money-popup-crack.pdf',
  'cover-4.jpg',
  'cover-6.jpg',
  'large-news.txt',
  'nauru-6015-small-fighter-left-gender.psd',
  'tv-xs.doc',
  'gustavia-entertainment-productivity.docx',
  'vintage-bahrain-saipan.xls',
  'indonesia-quito-nancy-grace-left-glad.xlsx',
  'legislation-grain.zip',
  'large-energy-dry-philippines.rar',
  'footer-243-ecuador.iso',
  'kyrgyzstan-04795009-picabo-street-guide-style.ai',
  'india-data-large-gk-chesterton-mother.esp',
  'footer-barbados-celine-dion.ppt',
  'socio-respectively-366996.pptx',
  'socio-ahead-531437-sweden-popup.wav',
  'trinidad-samuel-morse-bring.m4v',
  'cover-12.jpg',
  'cover-18.jpg',
  'xl-david-blaine-component-tanzania-books.pdf',
];

const URLS = [
  _mock.image.cover(1),
  'https://www.cloud.com/s/c218bo6kjuqyv66/design_suriname_2015.mp3',
  'https://www.cloud.com/s/c218bo6kjuqyv66/expertise_2015_conakry_sao-tome-and-principe_gender.mp4',
  'https://www.cloud.com/s/c218bo6kjuqyv66/money-popup-crack.pdf',
  _mock.image.cover(3),
  _mock.image.cover(5),
  'https://www.cloud.com/s/c218bo6kjuqyv66/large_news.txt',
  'https://www.cloud.com/s/c218bo6kjuqyv66/nauru-6015-small-fighter-left-gender.psd',
  'https://www.cloud.com/s/c218bo6kjuqyv66/tv-xs.doc',
  'https://www.cloud.com/s/c218bo6kjuqyv66/gustavia-entertainment-productivity.docx',
  'https://www.cloud.com/s/c218bo6kjuqyv66/vintage_bahrain_saipan.xls',
  'https://www.cloud.com/s/c218bo6kjuqyv66/indonesia-quito-nancy-grace-left-glad.xlsx',
  'https://www.cloud.com/s/c218bo6kjuqyv66/legislation-grain.zip',
  'https://www.cloud.com/s/c218bo6kjuqyv66/large_energy_dry_philippines.rar',
  'https://www.cloud.com/s/c218bo6kjuqyv66/footer-243-ecuador.iso',
  'https://www.cloud.com/s/c218bo6kjuqyv66/kyrgyzstan-04795009-picabo-street-guide-style.ai',
  'https://www.cloud.com/s/c218bo6kjuqyv66/india-data-large-gk-chesterton-mother.esp',
  'https://www.cloud.com/s/c218bo6kjuqyv66/footer-barbados-celine-dion.ppt',
  'https://www.cloud.com/s/c218bo6kjuqyv66/socio_respectively_366996.pptx',
  'https://www.cloud.com/s/c218bo6kjuqyv66/socio_ahead_531437_sweden_popup.wav',
  'https://www.cloud.com/s/c218bo6kjuqyv66/trinidad_samuel-morse_bring.m4v',
  _mock.image.cover(11),
  _mock.image.cover(17),
  'https://www.cloud.com/s/c218bo6kjuqyv66/xl_david-blaine_component_tanzania_books.pdf',
];



const SHARED_PERSONS = [...Array(20)].map((_, index) => ({
  id: _mock.id(index),
  name: _mock.fullName(index),
  email: _mock.email(index),
  avatarUrl: _mock.image.avatar(index),
  permission: index % 2 ? 'view' : 'edit',
}));

export const FILE_TYPE_OPTIONS = [
  'folder',
  'txt',
  'zip',
  'audio',
  'image',
  'video',
  'word',
  'excel',
  'powerpoint',
  'pdf',
  'photoshop',
  'illustrator',
];

// ----------------------------------------------------------------------

const shared = (index) =>
  (index === 0 && SHARED_PERSONS.slice(0, 5)) ||
  (index === 1 && SHARED_PERSONS.slice(5, 9)) ||
  (index === 2 && SHARED_PERSONS.slice(9, 11)) ||
  (index === 3 && SHARED_PERSONS.slice(11, 12)) ||
  [];
let i= 1;
export const _folders = FOLDERS.map((name, index) => ({
  id: `${_mock.id(index)}_folder`,
  name,
  type: 'folder',
  url: URLS[index],
  shared: shared(index),
  tags: _tags.slice(0, 5),
  size: GB / ((index + 1) * 10),
  totalFiles: (index + 1) * 100,
  createdAt: _mock.time(index),
  modifiedAt: _mock.time(index),
  isFavorited: _mock.boolean(index + 1),
}));

export const _files = FILES.map((name, index) => ({
  id: `${_mock.id(index)}_file`,
  name,
  url: URLS[index],
  shared: shared(index),
  tags: _tags.slice(0, 5),
  size: GB / ((index + 1) * 500),
  createdAt: _mock.time(index),
  modifiedAt: _mock.time(index),
  type: `${name.split('.').pop()}`,
  isFavorited: _mock.boolean(index + 1),
}));
export const _clinics_corps =  CLINIC_CORP.map((name, index) => ({
  id: i++,
  name,
  url: URLS[index],
  shared: shared(index),
  tags: _tags.slice(0, 5),
  // size: GB / ((index + 1) * 500),
  createdAt: _mock.time(index),
  modifiedAt: _mock.time(index),
  type: `${name.split('.').pop()}`,     
  isFavorited: _mock.boolean(index + 1),
}));
// export const _clinics =  CLINIC.map((name, index) => ({
//   id: `${_mock.id(index)}_file`,
//   name,
//   url: URLS[index],
//   shared: shared(index),
//   tags: _tags.slice(0, 5),
//   size: GB / ((index + 1) * 500),
//   createdAt: _mock.time(index),
//   modifiedAt: _mock.time(index),
//   type: `${name.split('.').pop()}`,
//   isFavorited: _mock.boolean(index + 1),
// }));
export const _clinics =  CLINIC;

// export const _allFiles = [..._folders, ..._files,..._clinics_corps,..._clinics];
export const _allFiles = [..._clinics];
