// assets
import { countries } from "src/assets/data";
//
import { _mock } from "./_mock";

// ----------------------------------------------------------------------

export const USER_STATUS_OPTIONS = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
  // { value: 'banned', label: 'Banned' },
  // { value: 'rejected', label: 'Rejected' },
];
export const PUBLISH_STATUS_OPTIONS = [
  { value: "active", label: "Active" },
  { value: "retired", label: "Retired" },
  // { value: 'banned', label: 'Banned' },
  // { value: 'rejected', label: 'Rejected' },
];

export const _userAbout = {
  id: _mock.id(1),
  role: _mock.role(1),
  email: _mock.email(1),
  country: countries[1].label,
  school: _mock.companyName(2),
  company: _mock.companyName(1),
  coverUrl: _mock.image.cover(3),
  totalFollowers: _mock.number.nativeL(1),
  totalFollowing: _mock.number.nativeL(2),
  quote:
    "Tart I love sugar plum I love oat cake. Sweet roll caramels I love jujubes. Topping cake wafer..",
  socialLinks: {
    facebook: `https://www.facebook.com/caitlyn.kerluke`,
    instagram: `https://www.instagram.com/caitlyn.kerluke`,
    linkedin: `https://www.linkedin.com/in/caitlyn.kerluke`,
    twitter: `https://www.twitter.com/caitlyn.kerluke`,
  },
};

export const _userFollowers = [...Array(18)].map((_, index) => ({
  id: _mock.id(index),
  name: _mock.fullName(index),
  country: countries[index + 1].label,
  avatarUrl: _mock.image.avatar(index),
}));

export const _userFriends = [...Array(18)].map((_, index) => ({
  id: _mock.id(index),
  role: _mock.role(index),
  name: _mock.fullName(index),
  avatarUrl: _mock.image.avatar(index),
}));

export const _userGallery = [...Array(12)].map((_, index) => ({
  id: _mock.id(index),
  postedAt: _mock.time(index),
  title: _mock.postTitle(index),
  imageUrl: _mock.image.cover(index),
}));

export const _userFeeds = [...Array(3)].map((_, index) => ({
  id: _mock.id(index),
  createdAt: _mock.time(index),
  media: _mock.image.travel(index + 1),
  message: _mock.sentence(index),
  personLikes: [...Array(20)].map((__, personIndex) => ({
    name: _mock.fullName(personIndex),
    avatarUrl: _mock.image.avatar(personIndex + 2),
  })),
  comments: (index === 2 && []) || [
    {
      id: _mock.id(7),
      author: {
        id: _mock.id(8),
        avatarUrl: _mock.image.avatar(index + 5),
        name: _mock.fullName(index + 5),
      },
      createdAt: _mock.time(2),
      message: "Praesent venenatis metus at",
    },
    {
      id: _mock.id(9),
      author: {
        id: _mock.id(10),
        avatarUrl: _mock.image.avatar(index + 6),
        name: _mock.fullName(index + 6),
      },
      createdAt: _mock.time(3),
      message:
        "Etiam rhoncus. Nullam vel sem. Pellentesque libero tortor, tincidunt et, tincidunt eget, semper nec, quam. Sed lectus.",
    },
  ],
}));

export const _userCards = [...Array(21)].map((_, index) => ({
  id: _mock.id(index),
  role: _mock.role(index),
  name: _mock.fullName(index),
  coverUrl: _mock.image.cover(index),
  avatarUrl: _mock.image.avatar(index),
  totalFollowers: _mock.number.nativeL(index),
  totalPosts: _mock.number.nativeL(index + 2),
  totalFollowing: _mock.number.nativeL(index + 1),
}));

export const _userPayment = [...Array(3)].map((_, index) => ({
  id: _mock.id(index),
  cardNumber: [
    "**** **** **** 1234",
    "**** **** **** 5678",
    "**** **** **** 7878",
  ][index],
  cardType: ["mastercard", "visa", "visa"][index],
  primary: index === 1,
}));

export const _userAddressBook = [...Array(4)].map((_, index) => ({
  id: _mock.id(index),
  primary: index === 0,
  name: _mock.fullName(index),
  phoneNumber: _mock.phoneNumber(index),
  fullAddress: _mock.fullAddress(index),
  addressType: (index === 0 && "Home") || "Office",
}));

export const _userInvoices = [...Array(10)].map((_, index) => ({
  id: _mock.id(index),
  invoiceNumber: `INV-199${index}`,
  createdAt: _mock.time(index),
  price: _mock.number.price(index),
}));

export const _userPlans = [
  {
    subscription: "basic",
    price: 0,
    primary: false,
  },
  {
    subscription: "starter",
    price: 4.99,
    primary: true,
  },
  {
    subscription: "premium",
    price: 9.99,
    primary: false,
  },
];

// export const _userList = [...Array(20)].map((_, index) => ({
export const _userList = [...Array(55)].map((_, index) => ({
  id: _mock.id(index),
  zipCode: "85807",
  state: "Virginia",
  city: "Rancho Cordova",
  role: _mock.role(index),
  email: _mock.email(index),
  address: "908 Jack Locks",
  name: _mock.fullName(index),
  isVerified: _mock.boolean(index),
  company: _mock.companyName(index),
  country: countries[index + 1].label,
  avatarUrl: _mock.image.avatar(index),
  phoneNumber: _mock.phoneNumber(index),
  clinic_name: _mock.clinic_name(index),
  corp_Name: _mock.corp_Name(index),
  stage: _mock.stage(index),
  todo: _mock.todo(index),
  asana_url: _mock.asana_url(index),
  actioBy: _mock.actioBy(index),

  status:
    // (index % 2 && 'pending') || (index % 3 && 'banned') || (index % 4 && 'rejected') || 'active',
    (index % 0 && "inactive") || "active",
  publishStatus:
    // (index % 2 && 'pending') || (index % 3 && 'banned') || (index % 4 && 'rejected') || 'active',
    (index % 2 && "retired") || "active",
}));


export const _userListTwo = {
  "status": true,
  "message": "success",
  "data": {
      "totalCount": 701,
      "pageSize": 15,
      "currentPage": 1,
      "totalPages": 47,
      "hasNext": true,
      "hasPrevious": false,
      "result": [
          {
              "id": 1,
              "office_number": "",
              "data_Path": "camgara_dental",
              "clinic_code": "",
              "corp_id": "123dental",
              "clinic_name": "BC-010 Camgara",
              "clinic_address": "",
              "clinic_address1": "",
              "clinic_postal": "",
              "clinic_city": "",
              "clinic_province": "",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Tracker",
              "runLedgerBalance": false,
              "adjustment": null,
              "payMethod": "{\r\n  \"Visa\": \"Visa\",\r\n  \"MasterCard\": \"M\",\r\n  \"PersCheque\": \"\",\r\n  \"InsCheque\": \"\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"\",\r\n  \"Debit\": \"\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\",\r\n  \"Finance\": \"\",\r\n  \"CreditCard\": \"\",\r\n  \"InsuranceETF\": \"\",\r\n  \"OtherMethods\": \"\",\r\n  \"InsuranceOthers\": \"\"\r\n}",
              "idclinics": 25,
              "dest_db": "camgaratracker",
              "cutoff_date": "2012-08-25T00:00:00",
              "acquistionDate": "2017-08-25T00:00:00",
              "firstTransId": "0",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "dmy",
              "stage": "5-Moved to Production",
              "todo": "none",
              "actioBy": "None <>",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": "",
              "locationId": "",
              "comments": "",
              "separateMultiClinicJail": false,
              "swellcx_locId": "0",
              "swellcx_teamId": "0",
              "swellcx_campaign": "0",
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": "",
              "data_path_source": null,
              "chargeAdj": "",
              "collectionAdj": ""
          },
          {
              "id": 2,
              "office_number": "",
              "data_Path": "barrie",
              "clinic_code": "1138",
              "corp_id": "altima",
              "clinic_name": "Altima Barrie",
              "clinic_address": "75 Collier Street",
              "clinic_address1": "",
              "clinic_postal": "L4M1G7",
              "clinic_city": "Barrie",
              "clinic_province": "ON",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Dentrix G6",
              "runLedgerBalance": false,
              "adjustment": "[\r\n  {\r\n    \"DefId\": \"1\",\r\n    \"Clinic_Path\": \"barrie_jail\",\r\n    \"Description\": \"+FEE DEBIT ADUSTMENT \",\r\n    \"chrg_adj_incl\": \"1\",\r\n    \"pmt_adj_incl\": \"False\",\r\n    \"prov_comp_incl\": \"False\",\r\n    \"idlgr_entry_map\": \"30\",\r\n    \"hyg_comp_incl\": \"1\"\r\n  },\r\n  {\r\n    \"DefId\": \"2\",\r\n    \"Clinic_Path\": \"barrie_jail\",\r\n    \"Description\": \"-FEE CREDIT ADJUSTMENT\",\r\n    \"chrg_adj_incl\": \"1\",\r\n    \"pmt_adj_incl\": \"False\",\r\n    \"prov_comp_incl\": \"False\",\r\n    \"idlgr_entry_map\": \"31\",\r\n    \"hyg_comp_incl\": \"1\"\r\n  },\r\n  {\r\n    \"DefId\": \"3\",\r\n    \"Clinic_Path\": \"barrie_jail\",\r\n    \"Description\": \"+PAYMENT REFUND \",\r\n    \"chrg_adj_incl\": \"False\",\r\n    \"pmt_adj_incl\": \"1\",\r\n    \"prov_comp_incl\": \"1\",\r\n    \"idlgr_entry_map\": \"32\",\r\n    \"hyg_comp_incl\": \"False\"\r\n  },\r\n  {\r\n    \"DefId\": \"4\",\r\n    \"Clinic_Path\": \"barrie_jail\",\r\n    \"Description\": \"-Write-Off\",\r\n    \"chrg_adj_incl\": \"1\",\r\n    \"pmt_adj_incl\": \"False\",\r\n    \"prov_comp_incl\": \"False\",\r\n    \"idlgr_entry_map\": \"33\",\r\n    \"hyg_comp_incl\": \"Fa",
              "payMethod": "{\r\n  \"Visa\": \"\",\r\n  \"MasterCard\": \"\",\r\n  \"PersCheque\": \"\",\r\n  \"InsCheque\": \"\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"\",\r\n  \"Debit\": \"\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\",\r\n  \"Finance\": \"\",\r\n  \"CreditCard\": \"\",\r\n  \"InsuranceETF\": \"\"\r\n}",
              "idclinics": 30,
              "dest_db": "barrie",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": "2013-05-28T00:00:00",
              "firstTransId": "0",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "ymd",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": "",
              "locationId": "",
              "comments": "",
              "separateMultiClinicJail": false,
              "swellcx_locId": "0",
              "swellcx_teamId": "0",
              "swellcx_campaign": "0",
              "timezone": "",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": "",
              "data_path_source": null,
              "chargeAdj": "",
              "collectionAdj": ""
          },
          {
              "id": 3,
              "office_number": "",
              "data_Path": "bayview",
              "clinic_code": "1114",
              "corp_id": "altima",
              "clinic_name": "Altima Bayview Village Dental Centre",
              "clinic_address": "2885 Bayview Avenue",
              "clinic_address1": "Unit #4",
              "clinic_postal": "M2K0A3",
              "clinic_city": "North York",
              "clinic_province": "ON",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Dentrix G6",
              "runLedgerBalance": true,
              "adjustment": "[\r\n  {\r\n    \"DefId\": \"1\",\r\n    \"Clinic_Path\": \"bayview_jail\",\r\n    \"Description\": \" +Do not use Opening Balance\",\r\n    \"chrg_adj_incl\": \"False\",\r\n    \"pmt_adj_incl\": \"1\",\r\n    \"prov_comp_incl\": \"1\",\r\n    \"idlgr_entry_map\": \"51\",\r\n    \"hyg_comp_incl\": \"False\"\r\n  },\r\n  {\r\n    \"DefId\": \"2\",\r\n    \"Clinic_Path\": \"bayview_jail\",\r\n    \"Description\": \" -Do not use Opening Balance\",\r\n    \"chrg_adj_incl\": \"False\",\r\n    \"pmt_adj_incl\": \"1\",\r\n    \"prov_comp_incl\": \"1\",\r\n    \"idlgr_entry_map\": \"51\",\r\n    \"hyg_comp_incl\": \"False\"\r\n  },\r\n  {\r\n    \"DefId\": \"3\",\r\n    \"Clinic_Path\": \"bayview_jail\",\r\n    \"Description\": \" +Fee Debit Adjustment\",\r\n    \"chrg_adj_incl\": \"1\",\r\n    \"pmt_adj_incl\": \"False\",\r\n    \"prov_comp_incl\": \"False\",\r\n    \"idlgr_entry_map\": \"30\",\r\n    \"hyg_comp_incl\": \"1\"\r\n  },\r\n  {\r\n    \"DefId\": \"4\",\r\n    \"Clinic_Path\": \"bayview_jail\",\r\n    \"Description\": \" -Fee Credit Adjustment\",\r\n    \"chrg_adj_incl\": \"1\",\r\n    \"pmt_adj_incl\": \"False\",\r\n    \"prov_comp_incl\": \"False\",\r\n    \"idlgr_entry_m",
              "payMethod": "{\r\n  \"Visa\": \"3\",\r\n  \"MasterCard\": \"4\",\r\n  \"PersCheque\": \"1\",\r\n  \"InsCheque\": \"7,9\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"6\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"2\",\r\n  \"Debit\": \"5\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"10,11,12,13,14,15\",\r\n  \"WebCoupon\": \"16,17,18\",\r\n  \"BatchCheque\": \"8\",\r\n  \"Finance\": \"\"\r\n}",
              "idclinics": 4,
              "dest_db": "bayview",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": "2013-06-10T00:00:00",
              "firstTransId": "0",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "dmy",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": null,
              "locationId": null,
              "comments": null,
              "separateMultiClinicJail": false,
              "swellcx_locId": null,
              "swellcx_teamId": null,
              "swellcx_campaign": null,
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 4,
              "office_number": "",
              "data_Path": "camgara_dental_data2",
              "clinic_code": "",
              "corp_id": "12002",
              "clinic_name": "Camgara Randall Allen",
              "clinic_address": "Camgara Dental Group, 7575 Cambie St.",
              "clinic_address1": "",
              "clinic_postal": "V6P 3H6",
              "clinic_city": "Vancouver",
              "clinic_province": "BC",
              "country": "CA",
              "clinic_phone": "(604) 325-8232",
              "clinic_fax": "",
              "clinic_email": "info@camgaradental.com",
              "clinic_appointmentunit": 10,
              "current_app": "Maxident",
              "runLedgerBalance": false,
              "adjustment": null,
              "payMethod": "{\r\n  \"Visa\": \"5\",\r\n  \"MasterCard\": \"4\",\r\n  \"PersCheque\": \"2\",\r\n  \"InsCheque\": \"\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"1\",\r\n  \"Debit\": \"3\",\r\n  \"DirectDeposit\": \"10\",\r\n  \"GiftCertificate\": \"\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\",\r\n  \"Finance\": \"\",\r\n  \"CreditCard\": \"\",\r\n  \"InsuranceETF\": \"\"\r\n}",
              "idclinics": 14,
              "dest_db": "camgara2",
              "cutoff_date": "2012-08-25T00:00:00",
              "acquistionDate": "2017-08-25T00:00:00",
              "firstTransId": "0",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "dmy",
              "stage": "5-Moved to Production",
              "todo": "none",
              "actioBy": "",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": "",
              "locationId": "",
              "comments": "Camgara Dental Group\r\n7575 Cambie St\r\nVancouver, BC\r\nV6P 3H6\r\n\r\n(604) 325-8232",
              "separateMultiClinicJail": false,
              "swellcx_locId": "0",
              "swellcx_teamId": "0",
              "swellcx_campaign": "0",
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 5,
              "office_number": "112",
              "data_Path": "bible_hill",
              "clinic_code": "1120",
              "corp_id": "altima",
              "clinic_name": "Bible Hill",
              "clinic_address": "336 Pictou Road",
              "clinic_address1": "",
              "clinic_postal": "B2N6H3",
              "clinic_city": "Truro",
              "clinic_province": "NS",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Abledent",
              "runLedgerBalance": false,
              "adjustment": "[]",
              "payMethod": "{\r\n  \"Visa\": \"V\",\r\n  \"MasterCard\": \"M\",\r\n  \"PersCheque\": \"Q\",\r\n  \"InsCheque\": \"R\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"P\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"\",\r\n  \"WriteOff\": \"W\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"C\",\r\n  \"Debit\": \"D\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\",\r\n  \"Finance\": \"\"\r\n}",
              "idclinics": 10,
              "dest_db": "biblehill",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": "2013-04-12T00:00:00",
              "firstTransId": "10537",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "dmy",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": null,
              "locationId": null,
              "comments": null,
              "separateMultiClinicJail": false,
              "swellcx_locId": null,
              "swellcx_teamId": null,
              "swellcx_campaign": null,
              "timezone": "15",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 6,
              "office_number": "1144",
              "data_Path": "strathroy",
              "clinic_code": "1144",
              "corp_id": "altima",
              "clinic_name": "Brightview Dental Strathroy",
              "clinic_address": "11 Methcalfe St W #1",
              "clinic_address1": "",
              "clinic_postal": "N7G1M7",
              "clinic_city": "Strathroy",
              "clinic_province": "ON",
              "country": "CA",
              "clinic_phone": "5192452020",
              "clinic_fax": "",
              "clinic_email": "strathroy@brightviewdental.ca",
              "clinic_appointmentunit": 10,
              "current_app": "Tracker",
              "runLedgerBalance": true,
              "adjustment": "[]",
              "payMethod": "{\r\n  \"Visa\": \"\",\r\n  \"MasterCard\": \"\",\r\n  \"PersCheque\": \"\",\r\n  \"InsCheque\": \"\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"\",\r\n  \"Debit\": \"\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\"\r\n}",
              "idclinics": 36,
              "dest_db": "strathroy",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": null,
              "firstTransId": null,
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "dmy",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": null,
              "locationId": null,
              "comments": null,
              "separateMultiClinicJail": false,
              "swellcx_locId": null,
              "swellcx_teamId": null,
              "swellcx_campaign": null,
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 7,
              "office_number": "",
              "data_Path": "wheatland_dental",
              "clinic_code": "",
              "corp_id": "mazadreh",
              "clinic_name": "Wheatland Dental Centre",
              "clinic_address": "520 Centre St.",
              "clinic_address1": "",
              "clinic_postal": "S0H 0B0",
              "clinic_city": "Assiniboia",
              "clinic_province": "Saskatchewan",
              "country": "CA",
              "clinic_phone": "(306) 642-4435",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 15,
              "current_app": "Power Practice",
              "runLedgerBalance": false,
              "adjustment": null,
              "payMethod": "{\r\n  \"Visa\": \"V,V4,V3\",\r\n  \"MasterCard\": \"MC,MC4,MC3\",\r\n  \"PersCheque\": \"PDC,PDC4,PDC3,CH,CH4,CH3\",\r\n  \"InsCheque\": \"IC,IC4,IC3,BIC,BIC4,BIC3\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"BFCP,BFCI\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"C,C4,C3\",\r\n  \"Debit\": \"DC,DC4,DC3\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\",\r\n  \"Finance\": \"\",\r\n  \"CreditCard\": \"\",\r\n  \"InsuranceETF\": \"\",\r\n  \"OtherMethods\": \"\",\r\n  \"InsuranceOthers\": \"\"\r\n}",
              "idclinics": 3,
              "dest_db": "wheatlanddental",
              "cutoff_date": "1970-01-01T00:00:00",
              "acquistionDate": "2012-05-04T00:00:00",
              "firstTransId": "0",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "dmy",
              "stage": "5-Moved to Production",
              "todo": "Move to Production Server",
              "actioBy": "None <>",
              "asana_url": "https://app.asana.com/0/278014366639733/1116672445912931/f",
              "multiClinicJail": false,
              "jailDataDir": "",
              "locationId": "",
              "comments": "",
              "separateMultiClinicJail": false,
              "swellcx_locId": "0",
              "swellcx_teamId": "0",
              "swellcx_campaign": "0",
              "timezone": "15",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": "default@edmsdental.com",
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 8,
              "office_number": "1015",
              "data_Path": "college",
              "clinic_code": "7002",
              "corp_id": "altima",
              "clinic_name": "College Clinic",
              "clinic_address": "979 College Street",
              "clinic_address1": "",
              "clinic_postal": "M6H1A6",
              "clinic_city": "Toronto",
              "clinic_province": "ON",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Dentrix G6",
              "runLedgerBalance": false,
              "adjustment": null,
              "payMethod": "{\r\n  \"Visa\": \"3\",\r\n  \"MasterCard\": \"8\",\r\n  \"PersCheque\": \"1,7\",\r\n  \"InsCheque\": \"6,10\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"9\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"2\",\r\n  \"Debit\": \"5\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"12\",\r\n  \"WebCoupon\": \"4,11,13\",\r\n  \"BatchCheque\": \"\",\r\n  \"Finance\": \"\"\r\n}",
              "idclinics": 63,
              "dest_db": "college",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": "2012-07-06T00:00:00",
              "firstTransId": "0",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "dmy",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": null,
              "locationId": null,
              "comments": null,
              "separateMultiClinicJail": false,
              "swellcx_locId": null,
              "swellcx_teamId": null,
              "swellcx_campaign": null,
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 9,
              "office_number": "",
              "data_Path": "coxwell",
              "clinic_code": "2204",
              "corp_id": "altima",
              "clinic_name": "Coxwell",
              "clinic_address": "",
              "clinic_address1": "",
              "clinic_postal": "",
              "clinic_city": "",
              "clinic_province": "",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Dentrix G6",
              "runLedgerBalance": false,
              "adjustment": null,
              "payMethod": "{\r\n  \"Visa\": \"3\",\r\n  \"MasterCard\": \"4\",\r\n  \"PersCheque\": \"1,7\",\r\n  \"InsCheque\": \"6,8\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"9\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"2\",\r\n  \"Debit\": \"5\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\",\r\n  \"Finance\": \"\"\r\n}",
              "idclinics": 46,
              "dest_db": "coxwell",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": "2012-07-06T00:00:00",
              "firstTransId": "0",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "ymd",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": null,
              "locationId": null,
              "comments": null,
              "separateMultiClinicJail": false,
              "swellcx_locId": null,
              "swellcx_teamId": null,
              "swellcx_campaign": null,
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 701,
              "office_number": "",
              "data_Path": "44ee2885-69b7-4e15-814b-f7b28b40afe0",
              "clinic_code": "",
              "corp_id": "Gozar",
              "clinic_name": "Gozar Eastboro",
              "clinic_address": "3732 Innes Road. Unit 1",
              "clinic_address1": "",
              "clinic_postal": "K1W 0C8",
              "clinic_city": "Orleans",
              "clinic_province": "ON",
              "country": "CA",
              "clinic_phone": "(613) 841-6100",
              "clinic_fax": "",
              "clinic_email": "info@eastborodental.com",
              "clinic_appointmentunit": 10,
              "current_app": "Abledent",
              "runLedgerBalance": false,
              "adjustment": null,
              "payMethod": "",
              "idclinics": 10,
              "dest_db": "gozareastboromca",
              "cutoff_date": "1970-01-04T00:00:00",
              "acquistionDate": "2013-01-04T00:00:00",
              "firstTransId": "1",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "ymd",
              "stage": "5-Moved to Production",
              "todo": "Obtain login credential",
              "actioBy": "None <>",
              "asana_url": "https://app.asana.com/0/1133074613585546/513368416430564/f",
              "multiClinicJail": false,
              "jailDataDir": "",
              "locationId": "",
              "comments": "web: https://eastborodental.com/contact-us/",
              "separateMultiClinicJail": false,
              "swellcx_locId": "0",
              "swellcx_teamId": "0",
              "swellcx_campaign": "0",
              "timezone": "15",
              "setup_Date": "2023-11-16T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": "",
              "data_path_source": null,
              "chargeAdj": "",
              "collectionAdj": ""
          },
          {
              "id": 10,
              "office_number": "1504",
              "data_Path": "grasslands",
              "clinic_code": "1504",
              "corp_id": "altima",
              "clinic_name": "RDG - Grasslands",
              "clinic_address": "4533 Gordon Road",
              "clinic_address1": "",
              "clinic_postal": "S4W3B7",
              "clinic_city": "Regina",
              "clinic_province": "SK",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Dentrix G4",
              "runLedgerBalance": false,
              "adjustment": "[]",
              "payMethod": "{\r\n  \"Visa\": \"3\",\r\n  \"MasterCard\": \"4\",\r\n  \"PersCheque\": \"1,6\",\r\n  \"InsCheque\": \"9\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"7\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"2\",\r\n  \"Debit\": \"5\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"10,11,12\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\"\r\n}",
              "idclinics": 57,
              "dest_db": "grasslands",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": null,
              "firstTransId": null,
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "ymd",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": null,
              "locationId": null,
              "comments": null,
              "separateMultiClinicJail": false,
              "swellcx_locId": null,
              "swellcx_teamId": null,
              "swellcx_campaign": null,
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 11,
              "office_number": "1502",
              "data_Path": "normanview",
              "clinic_code": "1502",
              "corp_id": "altima",
              "clinic_name": "RDG - Normanview",
              "clinic_address": "398 McCarthy Blvd.",
              "clinic_address1": "",
              "clinic_postal": "S4R7M2",
              "clinic_city": "North Regina",
              "clinic_province": "SK",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Dentrix G4",
              "runLedgerBalance": false,
              "adjustment": "[]",
              "payMethod": "{\r\n  \"Visa\": \"3\",\r\n  \"MasterCard\": \"4\",\r\n  \"PersCheque\": \"1,7\",\r\n  \"InsCheque\": \"\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"8\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"2\",\r\n  \"Debit\": \"5\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"6\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\"\r\n}",
              "idclinics": 55,
              "dest_db": "normanview",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": null,
              "firstTransId": null,
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "dmy",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": null,
              "locationId": null,
              "comments": null,
              "separateMultiClinicJail": false,
              "swellcx_locId": null,
              "swellcx_teamId": null,
              "swellcx_campaign": null,
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 12,
              "office_number": "1506",
              "data_Path": "russell",
              "clinic_code": "1506",
              "corp_id": "altima",
              "clinic_name": "Altima Russell",
              "clinic_address": "1131 Concession St",
              "clinic_address1": "",
              "clinic_postal": "K4R1C8",
              "clinic_city": "Russell",
              "clinic_province": "ON",
              "country": "CA",
              "clinic_phone": "6134453505",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Dentrix G6",
              "runLedgerBalance": false,
              "adjustment": "[]",
              "payMethod": "{\r\n  \"Visa\": \"3\",\r\n  \"MasterCard\": \"4\",\r\n  \"PersCheque\": \"1\",\r\n  \"InsCheque\": \"7,9\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"6\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"2\",\r\n  \"Debit\": \"5\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"10,11,12,13,14,15\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"8\",\r\n  \"Finance\": \"\"\r\n}",
              "idclinics": 59,
              "dest_db": "russell",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": "2013-03-05T00:00:00",
              "firstTransId": "0",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "ymd",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": null,
              "locationId": null,
              "comments": null,
              "separateMultiClinicJail": false,
              "swellcx_locId": null,
              "swellcx_teamId": null,
              "swellcx_campaign": null,
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 13,
              "office_number": "1503",
              "data_Path": "southland",
              "clinic_code": "1503",
              "corp_id": "altima",
              "clinic_name": "RDG - Southland",
              "clinic_address": "65-2965 Gordon Road",
              "clinic_address1": "",
              "clinic_postal": "S4S6H7",
              "clinic_city": "Regina",
              "clinic_province": "SK",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Dentrix G4",
              "runLedgerBalance": false,
              "adjustment": "[]",
              "payMethod": "{\r\n  \"Visa\": \"3\",\r\n  \"MasterCard\": \"4\",\r\n  \"PersCheque\": \"1\",\r\n  \"InsCheque\": \"6\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"7\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"2\",\r\n  \"Debit\": \"5\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"9,10\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\"\r\n}",
              "idclinics": 56,
              "dest_db": "southland",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": null,
              "firstTransId": null,
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "ymd",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": null,
              "locationId": null,
              "comments": null,
              "separateMultiClinicJail": false,
              "swellcx_locId": null,
              "swellcx_teamId": null,
              "swellcx_campaign": null,
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": null,
              "data_path_source": null,
              "chargeAdj": null,
              "collectionAdj": null
          },
          {
              "id": 14,
              "office_number": "",
              "data_Path": "dundas",
              "clinic_code": "1133",
              "corp_id": "altima",
              "clinic_name": "Altima Dundas Square Dental Centre",
              "clinic_address": "2065 Dundas Street East",
              "clinic_address1": "Suite #109, ",
              "clinic_postal": "L4X2W1",
              "clinic_city": "Mississauga",
              "clinic_province": "ON",
              "country": "CA",
              "clinic_phone": "",
              "clinic_fax": "",
              "clinic_email": "",
              "clinic_appointmentunit": 10,
              "current_app": "Dentrix G6",
              "runLedgerBalance": true,
              "adjustment": "[\r\n  {\r\n    \"DefId\": \"18\",\r\n    \"Clinic_Path\": \"dundas_jail\",\r\n    \"Description\": \"  +Empty\",\r\n    \"chrg_adj_incl\": \"1\",\r\n    \"pmt_adj_incl\": \"False\",\r\n    \"prov_comp_incl\": \"False\",\r\n    \"idlgr_entry_map\": \"0\",\r\n    \"hyg_comp_incl\": \"False\"\r\n  },\r\n  {\r\n    \"DefId\": \"19\",\r\n    \"Clinic_Path\": \"dundas_jail\",\r\n    \"Description\": \"  +Empty\",\r\n    \"chrg_adj_incl\": \"1\",\r\n    \"pmt_adj_incl\": \"False\",\r\n    \"prov_comp_incl\": \"False\",\r\n    \"idlgr_entry_map\": \"0\",\r\n    \"hyg_comp_incl\": \"False\"\r\n  },\r\n  {\r\n    \"DefId\": \"20\",\r\n    \"Clinic_Path\": \"dundas_jail\",\r\n    \"Description\": \"  +Empty\",\r\n    \"chrg_adj_incl\": \"1\",\r\n    \"pmt_adj_incl\": \"False\",\r\n    \"prov_comp_incl\": \"False\",\r\n    \"idlgr_entry_map\": \"0\",\r\n    \"hyg_comp_incl\": \"False\"\r\n  },\r\n  {\r\n    \"DefId\": \"21\",\r\n    \"Clinic_Path\": \"dundas_jail\",\r\n    \"Description\": \"  +Empty\",\r\n    \"chrg_adj_incl\": \"1\",\r\n    \"pmt_adj_incl\": \"False\",\r\n    \"prov_comp_incl\": \"False\",\r\n    \"idlgr_entry_map\": \"0\",\r\n    \"hyg_comp_incl\": \"False\"\r\n  },\r\n  {\r\n    \"Def",
              "payMethod": "{\r\n  \"Visa\": \"Visa\",\r\n  \"MasterCard\": \"M\",\r\n  \"PersCheque\": \"\",\r\n  \"InsCheque\": \"\",\r\n  \"PayPlan\": \"\",\r\n  \"Balance\": \"\",\r\n  \"Refund\": \"\",\r\n  \"Amex\": \"\",\r\n  \"WriteOff\": \"\",\r\n  \"Assignment\": \"\",\r\n  \"Etransfer\": \"\",\r\n  \"Cash\": \"\",\r\n  \"Debit\": \"\",\r\n  \"DirectDeposit\": \"\",\r\n  \"GiftCertificate\": \"\",\r\n  \"WebCoupon\": \"\",\r\n  \"BatchCheque\": \"\",\r\n  \"Finance\": \"\",\r\n  \"CreditCard\": \"\",\r\n  \"InsuranceETF\": \"\",\r\n  \"OtherMethods\": \"\",\r\n  \"InsuranceOthers\": \"\"\r\n}",
              "idclinics": 23,
              "dest_db": "dundas",
              "cutoff_date": "2014-01-01T00:00:00",
              "acquistionDate": "2012-09-05T00:00:00",
              "firstTransId": "0",
              "prodDate": "EntryDate",
              "colDate": "EntryDate",
              "dateFormat": "dmy",
              "stage": "5-Moved to Production",
              "todo": "None",
              "actioBy": "None",
              "asana_url": "",
              "multiClinicJail": false,
              "jailDataDir": "",
              "locationId": "",
              "comments": "",
              "separateMultiClinicJail": false,
              "swellcx_locId": "0",
              "swellcx_teamId": "0",
              "swellcx_campaign": "0",
              "timezone": "+00:00",
              "setup_Date": "2020-09-27T00:00:00",
              "goLive_Date": null,
              "active": true,
              "staff": "",
              "data_path_source": null,
              "chargeAdj": "",
              "collectionAdj": ""
          }
      ]
  }
}